In [ ]:
import os
import json
import pandas as pd
import psycopg2
import streamlit as st 
import plotly.express as px
import plotly.colors as pc
import matplotlib.pyplot as plt

# agg_transaction
path1 =  "C:/Users/RAJ/pulse/data/aggregated/transaction/country/india/state/"
agg_trans_list = os.listdir(path1)

df_agg_trans = {'states':[], 'year':[], 'quarter':[], 'transaction_type':[], 'transaction_count':[], 'transaction_amount':[]}
for state in agg_trans_list:
    curr_state = path1 + state + "/"
    agg_year_list = os.listdir(curr_state)
    
    for year in agg_year_list:
        cur_year = curr_state + year +'/'
        agg_file_list = os.listdir(cur_year)
        
        for doc in agg_file_list:
            curr_doc = cur_year + doc
            data = open(curr_doc, 'r')
            
            a = json.load(data)
            
            for i in  a['data']['transactionData']:
                name = i['name']
                count = i['paymentInstruments'][0]['count']
                amount = i['paymentInstruments'][0]['amount']
                
                
                df_agg_trans['transaction_type'].append(name)
                df_agg_trans['transaction_count'].append(count)
                df_agg_trans['transaction_amount'].append(amount)
                df_agg_trans['states'].append(state)
                df_agg_trans['year'].append(year)
                df_agg_trans['quarter'].append(int(doc.strip('.json')))

            
aggregated_transaction = pd.DataFrame(df_agg_trans)
aggregated_transaction['states'] = aggregated_transaction['states'].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
aggregated_transaction['states'] = aggregated_transaction['states'].str.replace("-", " ")
aggregated_transaction['states'] = aggregated_transaction['states'].str.title()
aggregated_transaction['states'] = aggregated_transaction['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu', 'Dadra and Nagar Haveli and Daman and Diu')


path2 = "C:/Users/RAJ/pulse/data/aggregated/user/country/india/state/"

user_trans_states = os.listdir(path2)

df_agg_user = {'states':[], 'year':[], 'quarter':[], 'brands':[], 'transaction_count':[], 'percentage':[]}

for states in user_trans_states:
    curr_state = path2 + states + '/'
    agg_useryear_list = os.listdir(curr_state)
    
    for year in agg_useryear_list:
        all_year = curr_state + year + '/'
        doc_list = os.listdir(all_year)
        
        for doc in doc_list:
            curr_doc = all_year + doc
            data = open(curr_doc, 'r')
            
            b = json.load(data)
            
            
            try:
    
                for i in b['data']['usersByDevice']:
                    brand = i['brand']
                    count = i['count']
                    percentage = i['percentage']
                    df_agg_user['brands'].append(brand)
                    df_agg_user['transaction_count'].append(count)
                    df_agg_user['percentage'].append(percentage)
                    df_agg_user['states'].append(states)
                    df_agg_user['year'].append(year)
                    df_agg_user['quarter'].append(int(doc.strip('.json')))

            except:
                
                pass
            
aggrigated_user = pd.DataFrame(df_agg_user)
            
aggrigated_user['states'] = aggrigated_user['states'].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
aggrigated_user['states'] = aggrigated_user['states'].str.replace("-", " ")
aggrigated_user['states'] = aggrigated_user['states'].str.title()
aggrigated_user['states'] = aggrigated_user['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu', 'Dadra and Nagar Haveli and Daman and Diu')
            

# map transaction
path3 = "C:/Users/RAJ/pulse/data/map/transaction/hover/country/india/state/"

map_trans_states = os.listdir(path3)

df_map_trans = {'states':[], 'year':[], 'quarter':[], 'district':[], 'transaction_count':[], 'transaction_amount':[]}

for states in map_trans_states:
    curr_state = path3 + states + '/'
    agg_useryear_list = os.listdir(curr_state)
    
    for year in agg_useryear_list:
        all_year = curr_state + year + '/'
        doc_list = os.listdir(all_year)
        
        for doc in doc_list:
            curr_doc = all_year + doc
            data = open(curr_doc, 'r')
            
            c = json.load(data)
            
            for i in c['data']['hoverDataList']:
                    name = i['name']
                    count = i['metric'][0]['count']
                    amount = i['metric'][0]['amount']
                    df_map_trans['district'].append(name)
                    df_map_trans['transaction_count'].append(count)
                    df_map_trans['transaction_amount'].append(amount)
                    df_map_trans['states'].append(states)
                    df_map_trans['year'].append(year)
                    df_map_trans['quarter'].append(int(doc.strip('.json')))
                    
df_map_trans  = pd.DataFrame(df_map_trans)

df_map_trans['states'] = df_map_trans['states'].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
df_map_trans['states'] = df_map_trans['states'].str.replace("-", " ")
df_map_trans['states'] = df_map_trans['states'].str.title()
df_map_trans['states'] = df_map_trans['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu', 'Dadra and Nagar Haveli and Daman and Diu')
           

# map user
path4 = "C:/Users/RAJ/pulse/data/map/user/hover/country/india/state/"

map_user_states = os.listdir(path4)

df_map_user = {'states':[], 'year':[], 'quarter':[], 'district':[], 'registeredUsers':[], 'appOpens':[]}

for states in map_user_states:
    curr_state = path4 + states + '/'
    agg_useryear_list = os.listdir(curr_state)
    
    for year in agg_useryear_list:
        all_year = curr_state + year + '/'
        doc_list = os.listdir(all_year)
        
        for doc in doc_list:
            curr_doc = all_year + doc
            data = open(curr_doc, 'r')
            
            d = json.load(data)
            
            
            for i in d['data']['hoverData'].items():
                district = i[0]
                registeredUsers = i[1]['registeredUsers']
                appOpens = i[1]['appOpens']
                df_map_user['district'].append(district)
                df_map_user['registeredUsers'].append(registeredUsers)
                df_map_user['appOpens'].append(appOpens)
                df_map_user['states'].append(states)
                df_map_user['year'].append(year)
                df_map_user['quarter'].append(int(doc.strip('.json')))

df_map_user = pd.DataFrame(df_map_user)
df_map_user['states'] = df_map_user['states'].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
df_map_user['states'] = df_map_user['states'].str.replace("-", " ")
df_map_user['states'] = df_map_user['states'].str.title()
df_map_user['states'] = df_map_user['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu', 'Dadra and Nagar Haveli and Daman and Diu')


# top transaction
path5 = "C:/Users/RAJ/pulse/data/top/transaction/country/india/state/"

top_trans_state = os.listdir(path5)
df_top_trans = {'states':[], 'year':[], 'quarter':[], 'pincodes':[], 'transaction_count':[], 'transaction_amount':[]}

for states in top_trans_state:
    curr_state = path5 + states + '/'
    agg_useryear_list = os.listdir(curr_state)
    
    for year in agg_useryear_list:
        all_year = curr_state + year + '/'
        doc_list = os.listdir(all_year)
        
        for doc in doc_list:
            curr_doc = all_year + doc
            data = open(curr_doc, 'r')
            
            e = json.load(data)
            print(e)
           
            for i in e['data']['pincodes']:
                entityName = i['entityName']
                count = i['metric']['count']
                amount = i['metric']['amount']
                df_top_trans['pincodes'].append(entityName)
                df_top_trans['transaction_count'].append(count)
                df_top_trans['transaction_amount'].append(amount)
                df_top_trans['states'].append(states)
                df_top_trans['year'].append(year)
                df_top_trans['quarter'].append(int(doc.strip('.json')))

            
df_top_trans = pd.DataFrame(df_top_trans)
df_top_trans['states'] = df_top_trans['states'].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
df_top_trans['states'] = df_top_trans['states'].str.replace("-", " ")
df_top_trans['states'] = df_top_trans['states'].str.title()
df_top_trans['states'] = df_top_trans['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu', 'Dadra and Nagar Haveli and Daman and Diu')


# top user
path6 = 'C:/Users/RAJ/pulse/data/top/user/country/india/state/'
top_user_state = os.listdir(path6)

df_top_user = {'states':[], 'year':[], 'quarter':[], 'pincodes':[], 'registeredUsers':[]}

for states in top_trans_state:
    curr_state = path6 + states + '/'
    agg_useryear_list = os.listdir(curr_state)
    
    for year in agg_useryear_list:
        all_year = curr_state + year + '/'
        doc_list = os.listdir(all_year)
        
        for doc in doc_list:
            curr_doc = all_year + doc
            data = open(curr_doc, 'r')
            
            f = json.load(data)
            
           
            for i in f['data']['pincodes']:
                entityName = i['name']
                registeredUsers = i['registeredUsers']
                df_top_user['pincodes'].append(entityName)
                df_top_user['registeredUsers'].append(registeredUsers)
                df_top_user['states'].append(states)
                df_top_user['year'].append(year)
                df_top_user['quarter'].append(int(doc.strip('.json')))

df_top_user = pd.DataFrame(df_top_user)
df_top_user['states'] = df_top_user['states'].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
df_top_user['states'] = df_top_user['states'].str.replace("-", " ")
df_top_user['states'] = df_top_user['states'].str.title()
df_top_user['states'] = df_top_user['states'].str.replace('Dadra & Nagar Haveli & Daman & Diu', 'Dadra and Nagar Haveli and Daman and Diu')


mydb = psycopg2.connect(host = 'localhost',
                       user = 'postgres',
                       port = '5432',
                       database ='phonepe',
                       password = 'Liverpool08#')
cursor = mydb.cursor()

query1 = '''CREATE TABLE aggregated_transaction(
                                        states varchar(250),
                                        year int,
                                        quarter int,
                                        transaction_type varchar(250),
                                        transaction_count bigint,
                                        transaction_amount bigint
                                        )'''
cursor.execute(query1)
mydb.commit()

insert_query1 = '''INSERT INTO aggregated_transaction(states, 
                                                        year, 
                                                        quarter, 
                                                        transaction_type, 
                                                        transaction_count,
                                                        transaction_amount)
                                                        
                                                        values(%s,%s,%s,%s,%s,%s)'''

data = aggregated_transaction.values.tolist()
cursor.executemany(insert_query1,data)
mydb.commit()


query2 = '''CREATE TABLE aggrigated_user(states varchar(250),
                                                year int,
                                                quarter int,
                                                brands varchar(250),
                                                transaction_count bigint,
                                                percentage float)'''
cursor.execute(query2)
mydb.commit()


insert_query2 = '''INSERT INTO aggrigated_user(
                                            states,
                                            year,
                                            quarter,
                                            brands,
                                            transaction_count,
                                            percentage)
                                            values(%s,%s,%s,%s,%s,%s)'''


data = aggrigated_user.values.tolist()
cursor.executemany(insert_query2,data)
mydb.commit()


query3 = '''CREATE TABLE df_map_trans(
                                    states varchar(250),
                                    year int,
                                    quarter int,
                                    district varchar(250),
                                    transaction_count bigint,
                                    transaction_amount bigint)'''
cursor.execute(query3)
mydb.commit()

insert_query3 = '''INSERT INTO df_map_trans(
                                            states,
                                            year,
                                            quarter,
                                            district,
                                            transaction_count,
                                            transaction_amount)
                                            values(%s,%s,%s,%s,%s,%s)'''


data = df_map_trans.values.tolist()
cursor.executemany(insert_query3,data)
mydb.commit()


query4 = '''CREATE TABLE df_map_user(
                                    states varchar(250),
                                    year int,
                                    quarter int,
                                    district varchar(250),
                                    registeredUsers bigint,
                                    appOpens bigint)'''
cursor.execute(query4)
mydb.commit()

insert_query4 = '''INSERT INTO df_map_user(
                                            states,
                                            year,
                                            quarter,
                                            district,
                                            registeredUsers,
                                            appOpens)
                                            values(%s,%s,%s,%s,%s,%s)'''


data = df_map_user.values.tolist()
cursor.executemany(insert_query4,data)
mydb.commit()


query5 = '''CREATE TABLE df_top_trans(
                                    states varchar(250),
                                    year int,
                                    quarter int,
                                    pincodes bigint,
                                    transaction_count bigint,
                                    transaction_amount bigint)'''
cursor.execute(query5)
mydb.commit()

insert_query5 = '''INSERT INTO df_top_trans(
                                            states,
                                            year,
                                            quarter,
                                            pincodes,
                                            transaction_count,
                                            transaction_amount)
                                            values(%s,%s,%s,%s,%s,%s)'''


data = df_top_trans.values.tolist()
cursor.executemany(insert_query5,data)
mydb.commit()


query6 = '''CREATE TABLE df_top_user(
                                    states varchar(250),
                                    year int,
                                    quarter int,
                                    pincodes bigint,
                                    registeredUsers bigint
                                    )'''
cursor.execute(query6)
mydb.commit()

insert_query6 = '''INSERT INTO df_top_user(
                                            states,
                                            year,
                                            quarter,
                                            pincodes,
                                            registeredUsers
                                            )
                                            values(%s,%s,%s,%s,%s)'''


data = df_top_user.values.tolist()
cursor.executemany(insert_query6,data)
mydb.commit()